CREATE INDEX IDX_TPD_TODAY_PLAN_ID ON T_TODAY_PLAN_DETAIL ("TODAY_PLAN_ID" ASC);
CREATE INDEX IDX_TPD_WORD_ID ON T_TODAY_PLAN_DETAIL ("WORD_ID" ASC);

CREATE INDEX IDX_USER_LOGIN ON T_USER ("LOGIN" ASC);
CREATE INDEX IDX_USER_IS_DELETE ON T_USER ("IS_DELETE" ASC);
CREATE INDEX IDX_USER_IS_ADMINISTRATORS ON T_USER ("IS_ADMINISTRATORS" ASC);

CREATE INDEX IDX_ULPARAMS_USER_ID ON T_USER_LEARNING_PARAMS ("USER_ID" ASC);

CREATE INDEX IDX_ULP_USER_ID ON T_USER_LEARNING_PLAN ("USER_ID" ASC);
CREATE INDEX IDX_ULP_WORD_ID ON T_USER_LEARNING_PLAN ("WORD_ID" ASC);

CREATE INDEX IDX_UTP_USER_ID ON T_USER_TODAY_PLAN ("USER_ID" ASC);