CREATE TABLE IF NOT EXISTS [T_WORD_REPOSITORY] (
[ID] VARCHAR(32)  NULL PRIMARY KEY,
[WORD] VARCHAR(2000)  NULL,
[US_PHONETIC] VARCHAR(2000)  NULL,
[UK_PHONETIC] VARCHAR(2000)  NULL,
[WORD_TRANSLATE] VARCHAR(2000)  NULL,
[WEB_TRANSLATE] VARCHAR(2000)  NULL,
[SAMPLE_SENTENCES] VARCHAR(2000)  NULL,
[CREATED_USER] VARCHAR(32)  NULL,
[CREATED_DATE] DATE  NULL,
[UPDATED_USER] VARCHAR(32)  NULL,
[UPDATED_DATE] DATE  NULL
)