CREATE TABLE IF NOT EXISTS [T_TODAY_PLAN_DETAIL] (
[ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
[TODAY_PLAN_ID] VARCHAR(32)  NULL,
[WORD_ID] VARCHAR(32)  NULL,
[IS_ERROR] INTEGER NOT NULL DEFAULT 0,
[OCCURRENCE_NUM] INTEGER NOT NULL DEFAULT 0,
[SORT_NUM] INTEGER NOT NULL DEFAULT 0
)