CREATE TABLE IF NOT EXISTS [User] (
[ID] VARCHAR(32)  NULL PRIMARY KEY,
[QUESTION] VARCHAR(2000)  NULL,
[REMINDER] VARCHAR(2000)  NULL,
[TRANSLATE] VARCHAR(2000)  NULL,
[CREATED_USER] VARCHAR(32)  NULL,
[CREATED_DATE] DATE  NULL,
[UPDATED_USER] VARCHAR(32)  NULL,
[UPDATED_DATE] DATE  NULL
)